### ISSUE TITLE
HTML検索と置換にて、「ブロック型入力」のURL入力のURL置換がされない

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#4704]
置換対処に、「ブロック型入力」の「URL入力」も含めるようにお願いいたします。
確認環境　シラサギ ver. 1.16.1

## 手順

リンクURLのドメインの差し替えを行うため、
[サイト内検索]-[HTML検索と置換]にて、URLでの検索しました。

記事は定型フォーム「ブロック型入力」の「URL入力」のものが検索結果として検出されます。
検出されますが、置換を実施しても、リンクURLが置換されませんでした。

**Comment by sunny4381** [comment]
fixed in https://github.com/shirasagi/shirasagi/commit/9e24fc6c546051deb961eed5372fb7e45ceb7413

ただし、修正は不十分で、再現テストを作成した。
https://github.com/shirasagi/shirasagi/tree/fix-4704-skel

---

ただし、内部的に「URL入力」は 1 から 2 へアップデートされており、1は過去との互換性のためにのみ残されており、機能の追加や修正は行っていません。
「URL入力」の version 1は置換されてないかもしれませんが、仕様制限となる点、ご了承いただければと思います。
